nelmio_api_doc:
  documentation:
    info:
      title: '%env(APP_NAME)%'
      version: '%env(APP_VERSION)%'
    servers:
      - url: '%env(APP_URL)%'
        description: API Gateway
  areas:
    path_patterns:
      - ^/api
