version: '3'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php83
    expose:
      - "9000"
    volumes:
      - ./:/var/www/project
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-data:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: